# make PFunction tests

test:
	cd python && $(MAKE)
	cd continuum_plasticity && $(MAKE)

clean: 
	cd commandline && $(MAKE) clean
	cd testlib && $(MAKE) clean
	cd continuum_plasticity && $(MAKE) clean
