# make PFunction tests

test:
	cd PFunction && $(MAKE)
	@#cd PField && $(MAKE)
	cd python && $(MAKE)

clean: 
	cd PFunction && $(MAKE) clean
	cd PField && $(MAKE) clean
	cd python && $(MAKE) clean
	cd testlib && $(MAKE) clean
