# make PFunction src

CSRC = c
CPPSRC = c++
PYTHONSRC = python

all:
    @cd CSRC; make
    @cd CPPSRC; make
    @cd PYTHONSRC; make

install:
	@cd CSRC; make install
    @cd CPPSRC; make install
    @cd PYTHONSRC; make install

uninstall:
	@cd CSRC; make uninstall
    @cd CPPSRC; make uninstall
    @cd PYTHONSRC; make uninstall

clean:
    @cd CSRC; make clean
    @cd CPPSRC; make clean
    @cd PYTHONSRC; make clean

